-- GENERATED by scripts/gen-pglite-schema.mjs from supabase migrations. DO NOT HAND-EDIT.
-- =============================================================================
-- local-schema-common.sql — REFERENCE / SYSTEM tables + infra for
-- hotseaters-ultimate. Applied FIRST on every per-user PGlite first-boot
-- (change-403 §403.b). Carries the version row, sync meta, the write-ahead
-- queue, and the system/reference entities (domain:'common' in sync-config.ts).
--
-- Implements ElectricSQL's "through-the-database" write pattern. For each
-- Tier-A entity (sync-config.ts) there are three objects:
--
--   <entity>_synced   immutable — Electric writes server rows here
--   <entity>_local    shadow    — optimistic local writes live here
--   <entity>          view      — synced + local merged; the app reads/writes
--
-- INSTEAD OF triggers on the view route writes to <entity>_local and append
-- a row to `local_writes`. A pg_notify on `local_write` drives the
-- write-path sync utility, which POSTs pending writes to Supabase and on
-- confirmation clears the optimistic row.
--
-- Self-hosted Supabase only. HotSeatersMVP is the bible.
-- Generated from migrations through 20260530000001.
-- =============================================================================

-- pgvector for local semantic search (S06). Embeddings are server-generated
-- and sync as ordinary vector columns; similarity runs locally via <=>.
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS _pglite_schema_version (
  id      INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  version TEXT    NOT NULL
);

-- DO NOTHING (not DO UPDATE): the boot-time migration check in
-- pglite-client.ts reads the STORED version AFTER re-applying this schema and
-- compares it to BUNDLED_PGLITE_SCHEMA_VERSION. Overwriting it here would make
-- the stored version always equal the bundled one, so a schema upgrade would
-- never be detected. Preserve the prior version; pglite-client stamps the new
-- one explicitly once the drop/re-hydrate migration has run.
INSERT INTO _pglite_schema_version (id, version)
  VALUES (1, '20260530000001')
  ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS _sync_meta (
  id              INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  tenant_id       TEXT,
  hydrated_at     TIMESTAMPTZ,
  schema_version  TEXT
);

INSERT INTO _sync_meta (id) VALUES (1)
  ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS local_writes (
  id          SERIAL PRIMARY KEY,
  txid        TEXT NOT NULL DEFAULT gen_random_uuid()::text,
  entity      TEXT NOT NULL,
  operation   TEXT NOT NULL CHECK (operation IN ('insert', 'update', 'delete')),
  row_id      TEXT NOT NULL,
  payload     JSONB,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  synced_at   TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_local_writes_pending
  ON local_writes (created_at) WHERE synced_at IS NULL;

-- =============================================================================
-- COMMON (domain:'common') ENTITIES
-- =============================================================================

-- ── metadata_type ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS metadata_type_synced (
  id                           TEXT,
  company_id                   TEXT,
  scope                        TEXT,
  name                         TEXT,
  description                  TEXT,
  is_active                    BOOLEAN,
  is_default                   BOOLEAN,
  "order"                      INTEGER,
  extra_schema                 JSONB,
  created_at                   TEXT,
  updated_at                   TEXT,
  is_sample                    BOOLEAN,
  created_by_id                TEXT,
  created_by                   TEXT
);

CREATE TABLE IF NOT EXISTS metadata_type_local (
  id                           TEXT,
  company_id                   TEXT,
  scope                        TEXT,
  name                         TEXT,
  description                  TEXT,
  is_active                    BOOLEAN,
  is_default                   BOOLEAN,
  "order"                      INTEGER,
  extra_schema                 JSONB,
  created_at                   TEXT,
  updated_at                   TEXT,
  is_sample                    BOOLEAN,
  created_by_id                TEXT,
  created_by                   TEXT,
  is_deleted                   BOOLEAN NOT NULL DEFAULT false
);

CREATE OR REPLACE VIEW metadata_type AS
  SELECT s.* FROM metadata_type_synced s
  WHERE NOT EXISTS (SELECT 1 FROM metadata_type_local l WHERE l.id = s.id)
  UNION ALL
  SELECT l.id, l.company_id, l.scope, l.name, l.description, l.is_active, l.is_default, l."order", l.extra_schema, l.created_at, l.updated_at, l.is_sample, l.created_by_id, l.created_by
  FROM metadata_type_local l
  WHERE NOT l.is_deleted;

CREATE OR REPLACE FUNCTION metadata_type_insert() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO metadata_type_local (id, company_id, scope, name, description, is_active, is_default, "order", extra_schema, created_at, updated_at, is_sample, created_by_id, created_by)
  VALUES (COALESCE(NEW.id, gen_random_uuid()::text), NEW.company_id, NEW.scope, NEW.name, NEW.description, NEW.is_active, NEW.is_default, NEW."order", NEW.extra_schema, NEW.created_at, NEW.updated_at, NEW.is_sample, NEW.created_by_id, NEW.created_by);
  INSERT INTO local_writes (entity, operation, row_id, payload)
  VALUES ('metadata_type', 'insert', NEW.id, to_jsonb(NEW));
  PERFORM pg_notify('local_write', 'metadata_type');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION metadata_type_update() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO metadata_type_local (id, company_id, scope, name, description, is_active, is_default, "order", extra_schema, created_at, updated_at, is_sample, created_by_id, created_by)
  VALUES (NEW.id, NEW.company_id, NEW.scope, NEW.name, NEW.description, NEW.is_active, NEW.is_default, NEW."order", NEW.extra_schema, NEW.created_at, NEW.updated_at, NEW.is_sample, NEW.created_by_id, NEW.created_by)
  ON CONFLICT (id) DO UPDATE SET
    company_id = EXCLUDED.company_id,
    scope = EXCLUDED.scope,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    is_active = EXCLUDED.is_active,
    is_default = EXCLUDED.is_default,
    "order" = EXCLUDED."order",
    extra_schema = EXCLUDED.extra_schema,
    updated_at = EXCLUDED.updated_at,
    is_sample = EXCLUDED.is_sample,
    created_by_id = EXCLUDED.created_by_id,
    created_by = EXCLUDED.created_by,
    is_deleted = false;
  INSERT INTO local_writes (entity, operation, row_id, payload)
  VALUES ('metadata_type', 'update', NEW.id, to_jsonb(NEW));
  PERFORM pg_notify('local_write', 'metadata_type');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION metadata_type_delete() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO metadata_type_local (id, is_deleted) VALUES (OLD.id, true)
  ON CONFLICT (id) DO UPDATE SET is_deleted = true;
  INSERT INTO local_writes (entity, operation, row_id, payload)
  VALUES ('metadata_type', 'delete', OLD.id, NULL);
  PERFORM pg_notify('local_write', 'metadata_type');
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS metadata_type_insert_trg ON metadata_type;
DROP TRIGGER IF EXISTS metadata_type_update_trg ON metadata_type;
DROP TRIGGER IF EXISTS metadata_type_delete_trg ON metadata_type;
CREATE TRIGGER metadata_type_insert_trg INSTEAD OF INSERT ON metadata_type
  FOR EACH ROW EXECUTE FUNCTION metadata_type_insert();
CREATE TRIGGER metadata_type_update_trg INSTEAD OF UPDATE ON metadata_type
  FOR EACH ROW EXECUTE FUNCTION metadata_type_update();
CREATE TRIGGER metadata_type_delete_trg INSTEAD OF DELETE ON metadata_type
  FOR EACH ROW EXECUTE FUNCTION metadata_type_delete();

-- ── entity_metadata ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS entity_metadata_synced (
  id                           TEXT,
  metadata_type_id             TEXT,
  company_id                   TEXT,
  multiplier                   NUMERIC,
  extra                        JSONB,
  created_at                   TEXT,
  updated_at                   TEXT,
  is_sample                    BOOLEAN,
  created_by_id                TEXT,
  created_by                   TEXT
);

CREATE TABLE IF NOT EXISTS entity_metadata_local (
  id                           TEXT,
  metadata_type_id             TEXT,
  company_id                   TEXT,
  multiplier                   NUMERIC,
  extra                        JSONB,
  created_at                   TEXT,
  updated_at                   TEXT,
  is_sample                    BOOLEAN,
  created_by_id                TEXT,
  created_by                   TEXT,
  is_deleted                   BOOLEAN NOT NULL DEFAULT false
);

CREATE OR REPLACE VIEW entity_metadata AS
  SELECT s.* FROM entity_metadata_synced s
  WHERE NOT EXISTS (SELECT 1 FROM entity_metadata_local l WHERE l.id = s.id)
  UNION ALL
  SELECT l.id, l.metadata_type_id, l.company_id, l.multiplier, l.extra, l.created_at, l.updated_at, l.is_sample, l.created_by_id, l.created_by
  FROM entity_metadata_local l
  WHERE NOT l.is_deleted;

CREATE OR REPLACE FUNCTION entity_metadata_insert() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO entity_metadata_local (id, metadata_type_id, company_id, multiplier, extra, created_at, updated_at, is_sample, created_by_id, created_by)
  VALUES (COALESCE(NEW.id, gen_random_uuid()::text), NEW.metadata_type_id, NEW.company_id, NEW.multiplier, NEW.extra, NEW.created_at, NEW.updated_at, NEW.is_sample, NEW.created_by_id, NEW.created_by);
  INSERT INTO local_writes (entity, operation, row_id, payload)
  VALUES ('entity_metadata', 'insert', NEW.id, to_jsonb(NEW));
  PERFORM pg_notify('local_write', 'entity_metadata');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION entity_metadata_update() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO entity_metadata_local (id, metadata_type_id, company_id, multiplier, extra, created_at, updated_at, is_sample, created_by_id, created_by)
  VALUES (NEW.id, NEW.metadata_type_id, NEW.company_id, NEW.multiplier, NEW.extra, NEW.created_at, NEW.updated_at, NEW.is_sample, NEW.created_by_id, NEW.created_by)
  ON CONFLICT (id) DO UPDATE SET
    metadata_type_id = EXCLUDED.metadata_type_id,
    company_id = EXCLUDED.company_id,
    multiplier = EXCLUDED.multiplier,
    extra = EXCLUDED.extra,
    updated_at = EXCLUDED.updated_at,
    is_sample = EXCLUDED.is_sample,
    created_by_id = EXCLUDED.created_by_id,
    created_by = EXCLUDED.created_by,
    is_deleted = false;
  INSERT INTO local_writes (entity, operation, row_id, payload)
  VALUES ('entity_metadata', 'update', NEW.id, to_jsonb(NEW));
  PERFORM pg_notify('local_write', 'entity_metadata');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION entity_metadata_delete() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO entity_metadata_local (id, is_deleted) VALUES (OLD.id, true)
  ON CONFLICT (id) DO UPDATE SET is_deleted = true;
  INSERT INTO local_writes (entity, operation, row_id, payload)
  VALUES ('entity_metadata', 'delete', OLD.id, NULL);
  PERFORM pg_notify('local_write', 'entity_metadata');
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS entity_metadata_insert_trg ON entity_metadata;
DROP TRIGGER IF EXISTS entity_metadata_update_trg ON entity_metadata;
DROP TRIGGER IF EXISTS entity_metadata_delete_trg ON entity_metadata;
CREATE TRIGGER entity_metadata_insert_trg INSTEAD OF INSERT ON entity_metadata
  FOR EACH ROW EXECUTE FUNCTION entity_metadata_insert();
CREATE TRIGGER entity_metadata_update_trg INSTEAD OF UPDATE ON entity_metadata
  FOR EACH ROW EXECUTE FUNCTION entity_metadata_update();
CREATE TRIGGER entity_metadata_delete_trg INSTEAD OF DELETE ON entity_metadata
  FOR EACH ROW EXECUTE FUNCTION entity_metadata_delete();
