-- DEPRECATED (change-403). Split into:
--   local-schema-common.sql  — reference / system tables
--   local-schema-user.sql    — tenanted tables per user
-- This file is no longer applied by pglite-client.ts.
-- Kept for reference only; do not edit.
