// Mobile entrypoint stub for Tauri 2 (iOS / Android).
//
// On mobile, Tauri generates the application entrypoint via the
// `tauri::mobile_entry_point` macro. For desktop, `src/main.rs` is used.
// This stub keeps the crate buildable as a library for the mobile target;
// the actual mobile entrypoint is generated by `tauri ios init` /
// `tauri android init` and wired through `gen/` (gitignored).

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
